services:
  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
#  api:
#      image: motorway-api
#      container_name: motorway-api
#      build:
#        context: ./motorway-api/
#        target: motorway-api
#      ports:
#        - 3000:3000